# -*- coding: utf-8 -*-
"""DTAT_CHALLENGE_Aloisio_Keulbeck.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WECQrMbaETF-2-Rtt5Jv3wxmvMpJOVey

# DATA CHALLENGE

---

Bem vindos ao primeiro DATA CHALLENGE!

Aqui traremos alguns problemas que envolvam python, dados, aprendizado de máquina e afins. O intuito é que vocês tentem ao máximo praticar com esses desafios que trarão por ventura, alguns tópicos interessantes.

# CHALLENGE: Funções

Um dia extra é adicionado ao calendário quase a cada quatro anos como 29 de fevereiro, e o dia é chamado de dia bissexto . Ele corrige o calendário pelo fato de que nosso planeta leva aproximadamente 365,25 dias para orbitar o sol. Um ano bissexto contém um dia bissexto.

No calendário gregoriano, três condições são usadas para identificar anos bissextos:

- O ano que pode ser dividido por 4, é um ano bissexto, a menos que:
  - O ano pode ser dividido por 100, então NÃO é um ano bissexto, a menos que:
    - O ano também é divisível por 400. Então é um ano bissexto.

Fonte: https://www.timeanddate.com/date/leapyear.html

Isso significa que no calendário gregoriano, os anos 2000 e 2400 são bissextos, enquanto 1800, 1900, 2100, 2200, 2300 e 2500 NÃO são anos bissextos.


## Tarefa

Dado um ano, determine se é um ano bissexto. Se for um ano bissexto, retorne o  `True`, caso contrário, retorne `False`.

Observe que o stub de código fornecido lê a entrada e passa argumentos para a função `is_leap`. Só é necessário completar a função `is_leap`.
"""

def is_leap(year):
    leap = False

    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False


year = int(input("Digite um ano: "))
print(is_leap(year))

# segunda forma para a solução

def is_leap(year):
    leap = (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0)
    return leap


year = int(input("Digite um ano: "))
print(is_leap(year))

"""# Observação:

Seu objetico é só escrever sua lógica dentro da função e enviar o seu arquivo para `profmatheus.pavani@fiap.com.br` e `profedgard.kiriyama@fiap.com.br` onde apenas executaremos seu código para testar, portanto: **É PROIBIDO ALTERAR A FUNÇÃO**, o que significa que você deve manter a estrutura, apenas colocando seu lógica dentro para apenas executarmos a célula de código.

Favor trocar o campo `seunomeaqui` no nome do arquivo para seu nome , exemplo:

- DTAT_CHALLENGE_matheuspavani.ipynb
"""